version: "3.9"
services:
  node-red:
    image: steineey/node-red-py:latest
    ports: 
      - "1880:1880"
    volumes:
      - "./data:/data"
    links:
      - "sql:database"
  sql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=MyPass@word"
      - "MSSQL_PID=Express"